events/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'events'
urlpatterns = [
    path('events/', views.eventsPage, name='events'),
    path('events/<int:eventID>/', views.eventDetail, name='eventDetail'),
    path('events/<int:eventID>/signup', views.signup, name='signup'),
    path('events/signupConfirm', views.signupConfirmation, name='confirmation'),
    path('events/<int:eventID>/admin', views.eventAdmin, name='eventAdmin'),
]

kit/urls.py
from django.urls import path

from . import views

app_name = 'kit'
urlpatterns = [
    path('kit', views.kitHome, name='kitHome'),
    path('kit/logout', views.kitLogout, name='kitLogout'),
    path('kit/borrowing', views.kitBorrowing, name='kitBorrowing'),
    path('kit/care', views.kitCare, name='kitCare'),
    path('kit/logout/takeBoard/<int:ID>', views.takeBoard, name='takeBoard'),
    path('kit/logout/returnBoard/<int:ID>', views.returnBoard, name='returnBoard'),
    path('kit/logout/takeSuit/<int:ID>', views.takeSuit, name='takeSuit'),
    path('kit/logout/returnSuit/<int:ID>', views.returnSuit, name='returnSuit'),
    path('kit/logout/takeMisc/<int:ID>', views.takeMisc, name='takeMisc'),
    path('kit/logout/returnMisc/<int:ID>', views.returnMisc, name='returnMisc'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import password_reset_request

urlpatterns = [
	path('', include('pages.urls')),
    path('', include('users.urls')),
    path('', include('events.urls')),
    path('', include('kit.urls')),
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),

    #Password Reset URLS
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset", password_reset_request, name="password_reset"),
]

admin.site.site_header = 'SuSurf Site Admin'
admin.site.site_title = 'SUSURF'

events/forms.py
from django import forms
from .models import Event, weekendSignupEntry, abroadSignupEntry, beginnerSignupEntry
from django.contrib.auth import get_user_model
 

class weekendSignupForm(forms.ModelForm):
    class Meta:
        model = weekendSignupEntry
        labels = {
            "borrowBoard": "Do you need to borrow a board?",
            "bringBoard": "Are you bringing a board?",
            "wetsuit": "Do you need to borrow a wetsuit?",
            "driveCar": "I can drive a car for this trip",
            "roofRacks": "Can you put a roofrack on your car?",
            "carSeats": "How many seats does your car have? (Inc. Driver)",
            "driveMinibus": "I can drive a Minibus for this trip",
            "tent": "If you own a tent how many people can it sleep?",
        }

        fields = [
            'borrowBoard',
            'bringBoard',
            'wetsuit',
            'driveCar',
            'roofRacks',
            'carSeats',
            'driveMinibus',
            'tent',
            'endQuestionAnswer',
        ]

        exclude = ['timestamp']

class abroadSignupForm(forms.ModelForm):
    class Meta:
        model = abroadSignupEntry
        labels = {
            "rental": "Do you want to rent equipment?",
            "lessons": "Do you want lessons?",
        }

        fields = [
            'rental',
            'lessons',
            'endQuestionAnswer',
        ]

        exclude = ['timestamp']

class beginnerSignupForm(forms.ModelForm):
    class Meta:
        model = beginnerSignupEntry
        labels = {
            "borrowBoard": "Do you need to borrow a board?",
            "wetsuit": "Do you need to borrow a wetsuit?",
            "driveCar": "I can drive a car for this trip",
            "roofRacks": "Can you put a roofrack on your car?",
            "carSeats": "How many seats does your car have? (Inc. Driver)",
        }

        fields = [
            'borrowBoard',
            'wetsuit',
            'driveCar',
            'roofRacks',
            'carSeats',
            'endQuestionAnswer',
        ]

        exclude = ['timestamp']

events/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.db import transaction
from django.utils import timezone
from django.core.mail import send_mail


from .models import Event
from .forms import weekendSignupForm, abroadSignupForm, beginnerSignupForm

from pages.models import BasePage


def eventsPage(request):
    basepage = BasePage.objects.get(version = "Default")
    futureEvents = Event.objects.all().order_by('startDateTime', 'name').filter(publishDateTime__lte=timezone.now()).filter(startDateTime__gte=timezone.now())
    pastEvents = Event.objects.all().order_by('-startDateTime', 'name').filter(publishDateTime__lte=timezone.now()).filter(startDateTime__lt=timezone.now())
    return render(request, 'events/eventsPage.html', {
        'futurelist': futureEvents,
        'pastlist': pastEvents,
        'currentPage': "Events",
        'footer': basepage.footer,
        'email': basepage.email,
        'title': basepage.title,
        'facebook': basepage.facebookLink,
        'instagram': basepage.instagramLink,
        'susu': basepage.susuLink,
                 })

def eventDetail(request, eventID):
    basepage = BasePage.objects.get(version = "Default")
    event = Event.objects.get(id=eventID)
    signup_active = False
    if event.signupRequired == True:
        if event.signupPublish == None:
            event.signupPublish = timezone.now()
            event.save()
        if event.signupClose == None:
            event.signupClose = timezone.now() + timezone.timedelta(days=14)
            event.save()
        if event.signupPublish <= timezone.now() < event.signupClose:
            signup_active = True
    return render(request, 'events/event_detail.html', {
    'event': event,
    'signup_active': signup_active,
    'currentPage': "Events",
    'footer': basepage.footer,
    'email': basepage.email,
    'title': basepage.title,
    'facebook': basepage.facebookLink,
    'instagram': basepage.instagramLink,
    'susu': basepage.susuLink,
             })

@login_required
def signup(request, eventID):
    basepage = BasePage.objects.get(version = "Default")
    event = Event.objects.get(id=eventID)

    if event.signupRequired == True:
        if event.signupPublish <= timezone.now() < event.signupClose:
            if event.event_type == 'Weekend Trip':
                if request.method == 'POST':
                    form = weekendSignupForm(request.POST)
                    if form.is_valid():
                        signupInstance = form.save()
                        signupInstance.user = request.user
                        signupInstance.save()
                        
                        event.weekendSignups.add(signupInstance)

                        #Confirmation Email
                        send_mail(
                            'Signup for {}'.format(event.name),
                            'Thanks for signing up for {}.\n\nThis email is not confirmation that you have a place on this {}.\nYou will be added to a group on Facebook if you have successfully made it on the event.\n\nIf you have any questions email info@susurf.co.uk'.format(event.name, event.event_type),
                            'enquiries.susurf@gmail.com',
                            [signupInstance.user.email],
                            fail_silently=True,
                        )

                        return redirect('events:confirmation')
                else:
                    form = weekendSignupForm()

            if event.event_type == 'Abroad Trip':
                if request.method == 'POST':
                    form = abroadSignupForm(request.POST)
                    if form.is_valid():
                        signupInstance = form.save()
                        signupInstance.user = request.user
                        signupInstance.save()
                        
                        event.abroadSignups.add(signupInstance)

                        #Confirmation Email
                        send_mail(
                            'Signup for {}'.format(event.name),
                            'Thanks for signing up for {}.\n\nThis email is not confirmation that you have a place on this {}.\nYou will be added to a group on Facebook if you have successfully made it on the event.\n\nIf you have any questions email info@susurf.co.uk'.format(event.name, event.event_type),
                            'enquiries.susurf@gmail.com',
                            [signupInstance.user.email],
                            fail_silently=False,
                        )

                        return redirect('events:confirmation')
                else:
                    form = abroadSignupForm()

            if event.event_type == 'Beginner Session':
                if request.method == 'POST':
                    form = beginnerSignupForm(request.POST)
                    if form.is_valid():
                        signupInstance = form.save()
                        signupInstance.user = request.user
                        signupInstance.save()
                        
                        event.beginnerSignups.add(signupInstance)

                        #Confirmation Email
                        send_mail(
                            'Signup for {}'.format(event.name),
                            'Thanks for signing up for {}.\n\nThis email is not confirmation that you have a place on this {}.\nYou will be added to a group on Facebook if you have successfully made it on the event.\n\nIf you have any questions email info@susurf.co.uk'.format(event.name, event.event_type),
                            'enquiries.susurf@gmail.com',
                            [signupInstance.user.email],
                            fail_silently=False,
                        )

                        return redirect('events:confirmation')
                else:
                    form = beginnerSignupForm()

            return render(request, 'events/eventSignup.html', {
                "form": form,
                "event": event,
                'currentPage': "Events",
                'footer': basepage.footer,
                'email': basepage.email,
                'title': basepage.title,
                'facebook': basepage.facebookLink,
                'instagram': basepage.instagramLink,
                'susu': basepage.susuLink
                          })
        else:
            return redirect('events:events') 
    else:
        return redirect('events:events')         

def signupConfirmation(request):
    basepage = BasePage.objects.get(version = "Default")
    return render(request, 'events/signupConfirmation.html', {
        'currentPage': "Events",
        'footer': basepage.footer,
        'email': basepage.email,
        'title': basepage.title,
        'facebook': basepage.facebookLink,
        'instagram': basepage.instagramLink,
        'susu': basepage.susuLink,
                 })

def eventAdmin(request, eventID):
    basepage = BasePage.objects.get(version = "Default")
    event = Event.objects.get(id=eventID)

    if event.event_type == 'Weekend Trip':
        signups = event.weekendSignups.all()
    if event.event_type == 'Abroad Trip':
        signups = event.abroadSignups.all()
    if event.event_type == 'Beginner Session':
        signups = event.beginnerSignups.all()

    if request.user.is_staff:
        return render(request, 'events/event_admin.html', {
        'event': event,
        'signups': signups,
        'currentPage': "Events",
        'footer': basepage.footer,
        'email': basepage.email,
        'title': basepage.title,
        'facebook': basepage.facebookLink,
        'instagram': basepage.instagramLink,
        'susu': basepage.susuLink,
                 })
    else:
        return redirect('events:events')

events/templates/events/eventSignup.html
{% extends "base.html" %}

{% block main %}

<div style="padding-top: 100px; padding-bottom: 100px;">
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="text-dark" style="padding-bottom: 2em;">Sign up for {{ event.name }}</h2>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name == "endQuestionAnswer" %}
                            {% if event.endQuestion != "" %}
                                <p>{{ event.endQuestion }}</p>
                                <p class="text-dark">
                                {{ field }}
                                {% if field.help_text %}
                                  <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                  <p style="color: red">{{ error }}</p>
                                {% endfor %}
                                </p>
                            {% endif %}
                        {% endif %}
                        {% if field.name == "tent" %}
                            {% if event.camping == True %}
                                <p class="text-dark">
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {% if field.help_text %}
                                  <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                  <p style="color: red">{{ error }}</p>
                                {% endfor %}
                                </p>
                            {% endif %}
                        {% endif %}
                        {% if field.name != "endQuestionAnswer" and field.name != "tent" %}
                            <p class="text-dark">
                            {{ field.label_tag }}<br>
                            {{ field }}
                            {% if field.help_text %}
                              <small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                              <p style="color: red">{{ error }}</p>
                            {% endfor %}
                            </p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Sign up</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

events/templates/events/event_admin.html
{% extends "base.html" %}

{% block js %}

<script>
function exportTableToExcel(tableID, filename = ''){
    var downloadLink;
    var dataType = 'application/vnd.ms-excel';
    var tableSelect = document.getElementById(tableID);
    var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');
    
    // Specify file name
    filename = filename?filename+'.xls':'excel_data.xls';
    
    // Create download link element
    downloadLink = document.createElement("a");
    
    document.body.appendChild(downloadLink);
    
    if(navigator.msSaveOrOpenBlob){
        var blob = new Blob(['\ufeff', tableHTML], {
            type: dataType
        });
        navigator.msSaveOrOpenBlob( blob, filename);
    }else{
        // Create a link to the file
        downloadLink.href = 'data:' + dataType + ', ' + tableHTML;
    
        // Setting the file name
        downloadLink.download = filename;
        
        //triggering the function
        downloadLink.click();
    }
}
</script>

{% endblock %}

{% block main %}
<div class="container-fluid" style="min-height: 80vh">
  <div class="container" style="padding-top: 2em; padding-bottom: 2em;">
    <h1>{{ event.name }} Admin</h1>
    <button id="exporttable" class="btn btn-success" onclick="exportTableToExcel('adminTable', filename = '{{event.name}}')">Export</button>
    {% if event.event_type == 'Weekend Trip' %}
    <div class="table-responsive">
      <table class="table table-striped table-hover" id="adminTable">
        <thead>
          <tr>
            <th scope="col">Time</th>
            <th scope="col">Name</th>
            <th scope="col">Dietary</th>
            <th scope="col">Ability</th>
            <th scope="col">Borrowing Board</th>
            <th scope="col">Bringing Board</th>
            <th scope="col">Wetsuit</th>
            <th scope="col">Can Drive</th>
            <th scope="col">Car Seats</th>
            <th scope="col">Roof Rack</th>
            <th scope="col">Can drive Minibus</th>
            {% if event.camping == True %}
            <th scope="col">My tent sleeps</th>
            {% endif %}
            <th scope="col">{{ event.endQuestion }}</th>
          </tr>
        </thead>
        <tbody>
          {% for entry in signups %}
            <tr>
            <td>{{ entry.timestamp|date:'m-d H:i:s' }}</td>
            <td>{{ entry.user.first_name }} {{ entry.user.last_name }}</td>
            <td>{{ entry.user.dietary }}</td>
            <td>{{ entry.user.ability }}</td>
            <td>{{ entry.borrowBoard }}</td>
            <td>{{ entry.bringBoard }}</td>
            <td>{{ entry.wetsuit }}</td>
            <td>{{ entry.driveCar }}</td>
            <td>{{ entry.carSeats }}</td>
            <td>{{ entry.roofRacks }}</td>
            <td>{{ entry.driveMinibus }}</td>
            {% if event.camping == True %}
            <td>{{ entry.tent }}</td>
            {% endif %}
            <td>{{ entry.endQuestionAnswer }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}


    {% if event.event_type == 'Abroad Trip' %}
    <div class="table-responsive">
      <table class="table" id="adminTable">
        <thead>
          <tr>
            <th scope="col">Time</th>
            <th scope="col">Name</th>
            <th scope="col">Dietary</th>
            <th scope="col">Ability</th>
            <th scope="col">Renting</th>
            <th scope="col">Lessons</th>
            <th scope="col">{{ event.endQuestion }}</th>
          </tr>
        </thead>
        <tbody>
          {% for entry in signups %}
            <tr>
            <td>{{ entry.timestamp|date:'m-d H:i:s' }}</td>
            <td>{{ entry.user.first_name }} {{ entry.user.last_name }}</td>
            <td>{{ entry.user.dietary }}</td>
            <td>{{ entry.user.ability }}</td>
            <td>{{ entry.rental }}</td>
            <td>{{ entry.lessons }}</td>
            <td>{{ entry.endQuestionAnswer }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}


    {% if event.event_type == 'Beginner Session' %}
    <div class="table-responsive">
      <table class="table" id="adminTable">
        <thead>
          <tr>
            <th scope="col">Time</th>
            <th scope="col">Name</th>
            <th scope="col">Ability</th>
            <th scope="col">Borrowing Board</th>
            <th scope="col">Wetsuit</th>
            <th scope="col">Can Drive</th>
            <th scope="col">Car Seats</th>
            <th scope="col">Roof Rack</th>
            <th scope="col">{{ event.endQuestion }}</th>
          </tr>
        </thead>
        <tbody>
          {% for entry in signups %}
            <tr>
            <td>{{ entry.timestamp|date:'m-d H:i:s' }}</td>
            <td>{{ entry.user.first_name }} {{ entry.user.last_name }}</td>
            <td>{{ entry.user.ability }}</td>
            <td>{{ entry.borrowBoard }}</td>
            <td>{{ entry.wetsuit }}</td>
            <td>{{ entry.driveCar }}</td>
            <td>{{ entry.carSeats }}</td>
            <td>{{ entry.roofRacks }}</td>
            <td>{{ entry.endQuestionAnswer }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}
  </div>
</div>


{% endblock %}

events/templates/events/event_detail.html
{% extends "base.html" %}

{% block main %}
<div class="container-fluid" style="min-height: 80vh; max-width: 100vw;">
  <div class="container" style="padding-top: 2em; padding-bottom: 2em;">
    <div class="row">
      <div class="col">
        <h1>{{ event.name }}</h1>
      </div>
    </div>
      <hr>
    <div class="row">
      <div class="col" style="width: 100%;">
        <p>{{ event.longDescription|linebreaks|urlize }}</p>
      </div>
    </div>
    <hr>
    <div class="row" style="text-align: center; padding-top: 1em; padding-bottom: 1em;">
      <div class="col-md">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="48" height="48"><path d="M12 13.5a2.5 2.5 0 100-5 2.5 2.5 0 000 5z"></path><path fill-rule="evenodd" d="M19.071 3.429C15.166-.476 8.834-.476 4.93 3.429c-3.905 3.905-3.905 10.237 0 14.142l.028.028 5.375 5.375a2.359 2.359 0 003.336 0l5.403-5.403c3.905-3.905 3.905-10.237 0-14.142zM5.99 4.489A8.5 8.5 0 0118.01 16.51l-5.403 5.404a.859.859 0 01-1.214 0l-5.378-5.378-.002-.002-.023-.024a8.5 8.5 0 010-12.02z"></path></svg> 
        <h3>
          {{ event.location }}
        </h3>
      </div>
      <div class="col-md">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="48" height="48"><path fill-rule="evenodd" d="M6.75 0a.75.75 0 01.75.75V3h9V.75a.75.75 0 011.5 0V3h2.75c.966 0 1.75.784 1.75 1.75v16a1.75 1.75 0 01-1.75 1.75H3.25a1.75 1.75 0 01-1.75-1.75v-16C1.5 3.784 2.284 3 3.25 3H6V.75A.75.75 0 016.75 0zm-3.5 4.5a.25.25 0 00-.25.25V8h18V4.75a.25.25 0 00-.25-.25H3.25zM21 9.5H3v11.25c0 .138.112.25.25.25h17.5a.25.25 0 00.25-.25V9.5z"></path></svg> 
        <h3>
          {{ event.startDateTime.date }}
          {% if event.startDateTime.date != event.endDateTime.date %}
           - {{ event.endDateTime.date }}
          {% endif %}
        </h3> 
      </div>
      <div class="col-md">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="48" height="48"><path d="M12.5 7.25a.75.75 0 00-1.5 0v5.5c0 .27.144.518.378.651l3.5 2a.75.75 0 00.744-1.302L12.5 12.315V7.25z"></path><path fill-rule="evenodd" d="M12 1C5.925 1 1 5.925 1 12s4.925 11 11 11 11-4.925 11-11S18.075 1 12 1zM2.5 12a9.5 9.5 0 1119 0 9.5 9.5 0 01-19 0z"></path></svg> 
        <h3>
          {{ event.startDateTime.time }}
          {% if event.startDateTime.date == event.endDateTime.date %} 
           - {{ event.endDateTime.time }}
          {% endif %} 
        </h3>
      </div>
    </div>
    <hr>
    <div class="row" style="text-align: center; padding-top: 1em; padding-bottom: 1em;">
      {% if event.signupRequired == True %}
      <div class="col-md">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="48" height="48"><path fill-rule="evenodd" d="M5.873 3.26A.75.75 0 016.44 3h11.31a.75.75 0 01.576.27l5 6a.75.75 0 01-.028.992l-10.75 11.5a.75.75 0 01-1.096 0l-10.75-11.5a.75.75 0 01-.02-1.003l5.19-6zm.91 1.24L2.258 9.73 12 20.153l9.75-10.43L17.399 4.5H6.783z"></path></svg>
        <h3>
          {% if event.cost != None %}
            £{{ event.cost }}
          {% endif %}
          {% if event.cost == None %}
            It's Freeeee!
          {% endif %}
        </h3>
      </div>
      {% endif %}
      <div class="col-md">
        {% if event.spaces != None %}
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="48" height="48"><path fill-rule="evenodd" d="M3.5 8a5.5 5.5 0 118.596 4.547 9.005 9.005 0 015.9 8.18.75.75 0 01-1.5.045 7.5 7.5 0 00-14.993 0 .75.75 0 01-1.499-.044 9.005 9.005 0 015.9-8.181A5.494 5.494 0 013.5 8zM9 4a4 4 0 100 8 4 4 0 000-8z"></path><path d="M17.29 8c-.148 0-.292.01-.434.03a.75.75 0 11-.212-1.484 4.53 4.53 0 013.38 8.097 6.69 6.69 0 013.956 6.107.75.75 0 01-1.5 0 5.193 5.193 0 00-3.696-4.972l-.534-.16v-1.676l.41-.209A3.03 3.03 0 0017.29 8z"></path></svg> 
          <h3>
            {{ event.spaces }} Spaces
          </h3>
        {% endif %}
      </div>
      <div class="col-md">
        {% if event.signupPublish != None %}
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="48" height="48"><path fill-rule="evenodd" d="M5.962 2.513a.75.75 0 01-.475.949l-.816.272a.25.25 0 00-.171.237V21.25c0 .138.112.25.25.25h14.5a.25.25 0 00.25-.25V3.97a.25.25 0 00-.17-.236l-.817-.272a.75.75 0 01.474-1.424l.816.273A1.75 1.75 0 0121 3.97v17.28A1.75 1.75 0 0119.25 23H4.75A1.75 1.75 0 013 21.25V3.97a1.75 1.75 0 011.197-1.66l.816-.272a.75.75 0 01.949.475z"></path><path fill-rule="evenodd" d="M7 1.75C7 .784 7.784 0 8.75 0h6.5C16.216 0 17 .784 17 1.75v1.5A1.75 1.75 0 0115.25 5h-6.5A1.75 1.75 0 017 3.25v-1.5zm1.75-.25a.25.25 0 00-.25.25v1.5c0 .138.112.25.25.25h6.5a.25.25 0 00.25-.25v-1.5a.25.25 0 00-.25-.25h-6.5z"></path></svg>
          <h3>
            Signup {{ event.signupPublish|date:"M" }}.  {{ event.signupPublish.day }}{{ event.signupPublish|date:"S" }}  {{ event.signupPublish.time }}
          </h3>
        {% endif %}
      </div>
    </div>
    {% if event.signupRequired == True %}
      {% if signup_active == True %}
        <div class="row" style="text-align: center;">
          <div class="col">
            <a role="button" class="btn btn-dark" href="{% url 'events:signup' eventID=event.id %}">Sign Up</a>
          </div>
        </div>
      {% endif %}
    {% endif %}
    {% if request.user.is_staff == True %}
      {% if event.signupRequired == True %}
      <div class="row" style="text-align: center; padding-top: 2em;">
        <div class="col">
            <a role="button" class="btn btn-danger" href="{% url 'events:eventAdmin' eventID=event.id %}">View Signups</a>
        </div>
      </div>
      {% endif %}
    {% endif %}
  </div>
</div>

{% endblock %}

events/templates/events/signupConfirmation.html
{% extends 'base.html' %}

{% block style %}
html {height:100%;}
body {margin:0; padding:0; height:100%;}
{% endblock %}

{% block main %}
<div style="background-color: #195e83; height: 100%;">
    <div class="container" style="padding-top: 300px;">
      <h1 style="color: #cce7e8; text-align: center;">Signup Saved!</h1>
    </div>
</div>
{% endblock %}