blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = 'blog'
urlpatterns = [
    path('blog/', views.blogList, name='blogList'),  
    path('blog/<int:blogID>/', views.blogDetail, name='blogDetail'),  
]

kit/urls.py
from django.urls import path

from . import views

app_name = 'kit'
urlpatterns = [
    path('kit', views.kitHome, name='kitHome'),
    path('kit/logout', views.kitLogout, name='kitLogout'),
    path('kit/borrowing', views.kitBorrowing, name='kitBorrowing'),
    path('kit/care', views.kitCare, name='kitCare'),
    path('kit/logout/takeBoard/<int:ID>', views.takeBoard, name='takeBoard'),
    path('kit/logout/returnBoard/<int:ID>', views.returnBoard, name='returnBoard'),
    path('kit/logout/takeSuit/<int:ID>', views.takeSuit, name='takeSuit'),
    path('kit/logout/returnSuit/<int:ID>', views.returnSuit, name='returnSuit'),
    path('kit/logout/takeMisc/<int:ID>', views.takeMisc, name='takeMisc'),
    path('kit/logout/returnMisc/<int:ID>', views.returnMisc, name='returnMisc'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import password_reset_request

urlpatterns = [
	path('', include('pages.urls')),
    path('', include('users.urls')),
    path('', include('events.urls')),
    path('', include('kit.urls')),
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),

    #Password Reset URLS
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset", password_reset_request, name="password_reset"),
]

admin.site.site_header = 'SuSurf Site Admin'
admin.site.site_title = 'SUSURF'

blog/models.py
from django.db import models

class blog(models.Model):
    title = models.TextField()
    date = models.DateField(auto_now_add=True)
    author = models.CharField(max_length=50)

    text1 = models.TextField()
    pic1 = models.ImageField(upload_to="blog/", null=True, blank=True)
    text2 = models.TextField(blank=True)
    pic2 = models.ImageField(upload_to="blog/", null=True, blank=True)
    text3 = models.TextField(blank=True)
    pic3 = models.ImageField(upload_to="blog/", null=True, blank=True)
    text4 = models.TextField(blank=True)
    pic4 = models.ImageField(upload_to="blog/", null=True, blank=True)
    text5 = models.TextField(blank=True)
    pic5 = models.ImageField(upload_to="blog/", null=True, blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.db import transaction
from django.utils import timezone
from django.core.mail import send_mail

from .models import blog

from pages.models import BasePage

def blogList(request):
    basepage = BasePage.objects.get(version = "Default")
    blogs = blog.objects.all().order_by('date')
    return render(request, 'blog/blogList.html', {
        'currentPage': "Blog",
        'blogs': blogs,
        'footer': basepage.footer,
        'email': basepage.email,
        'title': basepage.title,
        'facebook': basepage.facebookLink,
        'instagram': basepage.instagramLink,
        'susu': basepage.susuLink,
                 })

@login_required
def blogDetail(request, blogID):
    basepage = BasePage.objects.get(version = "Default")
    Blog = blog.objects.get(id=blogID)
    return render(request, 'blog/blogDetail.html', {
    'blog': Blog,
    'currentPage': "Blog",
    'footer': basepage.footer,
    'email': basepage.email,
    'title': basepage.title,
    'facebook': basepage.facebookLink,
    'instagram': basepage.instagramLink,
    'susu': basepage.susuLink,
             })

blog/templates/blog/blogDetail.html
{% extends "base.html" %}

{% block style %}


#pic {
    width:100%;
    height:auto;
    border: 1px solid #000;
    }

{% endblock %}

{% block main %}
<div class="container-fluid" style="min-height: 80vh">
  <div class="container" style="padding-top: 2em; padding-bottom: 2em;">
    <div class="row">
      <div class="col">
        <div class="d-flex">
            <div>
              <h2>{{blog.title}}</h2>
              <h5 class="text-muted">by {{blog.author}}</h5>
            </div>
            <div class="ml-auto">
              <h2>{{blog.date}}</h2>
            </div>
       </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col">
        <p>{{ blog.text1|linebreaks|urlize }}</p>
      </div>
    </div>
    {% if blog.pic1.url != null %}
    <div class="row">
      <div class="col">
        <img class="card-img-top" src="{{ blog.pic1.url }}" id="pic">
      </div>
    </div>
    {% endif %}

    {% if blog.text2 != null %}
    <div class="row">
      <div class="col">
        <p>{{ blog.text2|linebreaks|urlize }}</p>
      </div>
    </div>
    {% endif %}
    {% if blog.pic2.url != null %}
    <div class="row">
      <div class="col">
        <img class="card-img-top" src="{{ blog.pic2.url }}" id="pic">
      </div>
    </div>
    {% endif %}

    {% if blog.text3 != null %}
    <div class="row">
      <div class="col">
        <p>{{ blog.text3|linebreaks|urlize }}</p>
      </div>
    </div>
    {% endif %}
    {% if blog.pic3.url != null %}
    <div class="row">
      <div class="col">
        <img class="card-img-top" src="{{ blog.pic3.url }}" id="pic">
      </div>
    </div>
    {% endif %}

    {% if blog.text4 != null %}
    <div class="row">
      <div class="col">
        <p>{{ blog.text4|linebreaks|urlize }}</p>
      </div>
    </div>
    {% endif %}
    {% if blog.pic4.url != null %}
    <div class="row">
      <div class="col">
        <img class="card-img-top" src="{{ blog.pic4.url }}" id="pic">
      </div>
    </div>
    {% endif %}

    {% if blog.text5 != null %}
    <div class="row">
      <div class="col">
        <p>{{ blog.text5|linebreaks|urlize }}</p>
      </div>
    </div>
    {% endif %}
    {% if blog.pic5.url != null %}
    <div class="row">
      <div class="col">
        <img class="card-img-top" src="{{ blog.pic5.url }}" id="pic">
      </div>
    </div>
    {% endif %}
  </div>
</div>

{% endblock %}

blog/templates/blog/blogList.html
{% extends "base.html" %}

{% block main %}

<div class="container-fluid" style="min-height: 80vh">
    <div class="container" style="padding-top: 2em; padding-bottom: 8em;">
        <h2 style="text-align: center; padding-bottom: 2em;"><strong>Susurf Blog</strong></h2>
        {% for blog in blogs %}
        <div class="row-content" style="padding-top: 2em;">
            <div class="card bg-info">
                <div class="card-body">
                    <h5 class="card-title">
                        <div class="d-flex">
                          <div>
                            <a class="text-white" href="{% url 'blog:blogDetail' blogID=blog.id %}">{{blog.title}}</a>
                          </div>
                          <div class="ml-auto">
                            {{blog.date}}
                          </div>
                        </div>
                    </h5>
                    <h6 class="card-subtitle mb-2">{{blog.author}}</h6>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}