kit/urls.py
from django.urls import path

from . import views

app_name = 'kit'
urlpatterns = [
    path('kit', views.kitHome, name='kitHome'),
    path('kit/logout', views.kitLogout, name='kitLogout'),
    path('kit/borrowing', views.kitBorrowing, name='kitBorrowing'),
    path('kit/care', views.kitCare, name='kitCare'),
    path('kit/logout/takeBoard/<int:ID>', views.takeBoard, name='takeBoard'),
    path('kit/logout/returnBoard/<int:ID>', views.returnBoard, name='returnBoard'),
    path('kit/logout/takeSuit/<int:ID>', views.takeSuit, name='takeSuit'),
    path('kit/logout/returnSuit/<int:ID>', views.returnSuit, name='returnSuit'),
    path('kit/logout/takeMisc/<int:ID>', views.takeMisc, name='takeMisc'),
    path('kit/logout/returnMisc/<int:ID>', views.returnMisc, name='returnMisc'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import password_reset_request

urlpatterns = [
	path('', include('pages.urls')),
    path('', include('users.urls')),
    path('', include('events.urls')),
    path('', include('kit.urls')),
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),

    #Password Reset URLS
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset", password_reset_request, name="password_reset"),
]

admin.site.site_header = 'SuSurf Site Admin'
admin.site.site_title = 'SUSURF'

kit/models.py
from django.db import models

class Surfboard(models.Model):
    IDnumber = models.IntegerField(unique=True)
    location = models.TextField(default='Container')
    pastBorrowers = models.TextField(blank=True)
    
    BOARD_ABILITY = (
        ('Beginner', 'Beginner'),
        ('Intermediate', 'Intermediate'),
        ('Advanced', 'Advanced'),
    )

    brand = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    size = models.CharField(max_length=6)
    ability = models.CharField(choices=BOARD_ABILITY, max_length=20)
    watertight = models.BooleanField(default=True)
    condition = models.TextField(blank=True)

    def __str__(self):
        return self.brand

class Wetsuit(models.Model):
    IDnumber = models.IntegerField(unique=True)
    location = models.TextField(default='Container')
    pastBorrowers = models.TextField(blank=True)
    usable = models.BooleanField(default=True)
    
    WETSUIT_SIZES = (
        ('Childs age 16', 'Childs age 16'),
        ('Womens 6', 'Womens 6'),
        ('Womens 8', 'Womens 8'),
        ('Womens 10', 'Womens 10'),
        ('Womens 12', 'Womens 12'),
        ('Womens 14', 'Womens 14'),
        ('Womens 16', 'Womens 16'),
        ('Mens Small', 'Mens Small'),
        ('Mens Medium', 'Mens Medium'),
        ('Mens Large', 'Mens Large'),
        ('Mens Extra Large', 'Mens Extra Large'),
    )

    WETSUIT_THICKNESSES = (
        ('6/5mm', '6/5mm'),
        ('5/4/3mm', '5/4/3mm'),
        ('5/4mm', '5/4mm'),
        ('5/3mm', '5/3mm'),
        ('4/3mm', '4/3mm'),
        ('3/2mm', '3/2mm'),
    )

    brand = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    size = models.CharField(choices=WETSUIT_SIZES, max_length=30)
    thickness = models.CharField(choices=WETSUIT_THICKNESSES, max_length=10)
    condition = models.TextField(blank=True)

    def __str__(self):
        return self.brand

class Misc_Item(models.Model):
    IDnumber = models.IntegerField(unique=True)
    location = models.TextField(default='Container')
    pastBorrowers = models.TextField(blank=True)
    
    ITEM_TYPE = (
        ('Leash', 'Leash'),
        ('Indo Board', 'Indo Board'),
        ('Soft Roof Rack', 'Soft Roof Rack'),
        ('Other', 'Other'),
    )

    item_type = models.CharField(choices=ITEM_TYPE, max_length=50)
    brand = models.CharField(max_length=50)
    condition = models.TextField(blank=True)

    def __str__(self):
        return self.item_type

kit/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils import timezone

from pages.models import BasePage
from .models import Surfboard, Wetsuit, Misc_Item

def kitHome(request):
    basepage = BasePage.objects.get(version = "Default")
    return render(request, 'kit/kitHome.html', {
        'currentPage': "Kit",
        'footer': basepage.footer,
        'email': basepage.email,
        'title': basepage.title,
        'facebook': basepage.facebookLink,
        'instagram': basepage.instagramLink,
        'susu': basepage.susuLink,
                 })

def kitBorrowing(request):
    basepage = BasePage.objects.get(version = "Default")
    return render(request, 'kit/kitBorrowing.html', {
        'currentPage': "Kit",
        'footer': basepage.footer,
        'email': basepage.email,
        'title': basepage.title,
        'facebook': basepage.facebookLink,
        'instagram': basepage.instagramLink,
        'susu': basepage.susuLink,
                 })

def kitCare(request):
    basepage = BasePage.objects.get(version = "Default")
    return render(request, 'kit/kitCare.html', {
        'currentPage': "Kit",
        'footer': basepage.footer,
        'email': basepage.email,
        'title': basepage.title,
        'facebook': basepage.facebookLink,
        'instagram': basepage.instagramLink,
        'susu': basepage.susuLink,
                 })

@login_required
def kitLogout(request):
    basepage = BasePage.objects.get(version = "Default")
    surfboards = Surfboard.objects.all().order_by('IDnumber')
    wetsuits = Wetsuit.objects.all().order_by('IDnumber')
    misc = Misc_Item.objects.all().order_by('IDnumber')
    user = request.user
    return render(request, 'kit/kitLogout.html', {
        'surfboards': surfboards,
        'wetsuits': wetsuits,
        'misc': misc,
        'user': user,
        'currentPage': "Kit",
        'footer': basepage.footer,
        'email': basepage.email,
        'title': basepage.title,
        'facebook': basepage.facebookLink,
        'instagram': basepage.instagramLink,
        'susu': basepage.susuLink,
                 })

@login_required
def takeBoard(request, ID):
    board = Surfboard.objects.get(IDnumber=ID)
    if board.location == "Container":
        board.location = request.user.email
        board.pastBorrowers = board.pastBorrowers + request.user.first_name + " " + request.user.last_name + " - "+ request.user.email +" - " + timezone.now().strftime("%Y-%m-%d %H:%M:%S %Z") + ", \r\n"
        board.save()
        return redirect('kit:kitLogout')
    else:
        return redirect('kit:kitLogout')

@login_required
def returnBoard(request, ID):
    board = Surfboard.objects.get(IDnumber=ID)
    if board.location == request.user.email:
        board.location = "Container"
        board.save()
        return redirect('kit:kitLogout')
    else:
        return redirect('kit:kitLogout')

@login_required
def takeSuit(request, ID):
    suit = Wetsuit.objects.get(IDnumber=ID)
    if suit.location == "Container":
        suit.location = request.user.email
        suit.pastBorrowers = suit.pastBorrowers + request.user.first_name + " " + request.user.last_name + " - "+ request.user.email +" - " + timezone.now().strftime("%Y-%m-%d %H:%M:%S %Z") + ", \r\n"
        suit.save()
        return redirect('kit:kitLogout')
    else:
        return redirect('kit:kitLogout')

@login_required
def returnSuit(request, ID):
    suit = Wetsuit.objects.get(IDnumber=ID)
    if suit.location == request.user.email:
        suit.location = "Container"
        suit.save()
        return redirect('kit:kitLogout')
    else:
        return redirect('kit:kitLogout')

@login_required
def takeMisc(request, ID):
    misc = Misc_Item.objects.get(IDnumber=ID)
    if misc.location == "Container":
        misc.location = request.user.email
        misc.pastBorrowers = misc.pastBorrowers + request.user.first_name + " " + request.user.last_name + " - "+ request.user.email +" - " + timezone.now().strftime("%Y-%m-%d %H:%M:%S %Z") + ", \r\n"
        misc.save()
        return redirect('kit:kitLogout')
    else:
        return redirect('kit:kitLogout')

@login_required
def returnMisc(request, ID):
    misc = Misc_Item.objects.get(IDnumber=ID)
    if misc.location == request.user.email:
        misc.location = "Container"
        misc.save()
        return redirect('kit:kitLogout')
    else:
        return redirect('kit:kitLogout')

kit/templates/kit/kitBorrowing.html
{% extends "base.html" %}

{% block main %}

<div class="container-fluid" style="padding-top: 3em; padding-bottom: 6em;">
    <div class="row content">
        <div class="container">
            <h2><strong>How to borrow kit?</strong></h2>
            <p>Wondering how you can borrow a board and a suit from Susurf for your solo adventures? Look no further!</p>
            <h6>You will need a SuSurf Membership to borrow club kit! <a href="https://www.susu.org/groups/susurf" target="_blank">Membership</a></h6>
            <h5 style="padding-top: 2em">Step one</h5>
            <p>Read this guide on borrowing kit and the guide on how to <a href="{% url 'kit:kitCare' %}">look after club kit.</a></p>
            <h5>Step two</h5>
            <p>Decide what you want to borrow, and what sizes you'll need. If you don't have any kit yourself you'll likely need a surfboard, a leash, and a wetsuit.</p>
            <ul>
              <li>If you're a beginner you'll want to borrow a foamie! Around 7ft if you're small, up to around 9ft if you're bigger</li>
              <li>The length of the leash should be around the same as the board. Most club leashes are quite long though so don't worry if its not!</li>
              <li>Wetsuits come in S, M, L, XL etc for Men, and 6, 8, 10, 12, 14 etc for Women. For a general size guide check out <a href="https://www.ripcurl.eu/en/help/size-guides.html" target="_blank">this.</a> A "T" suffix means tall, and "S" means short.
            </ul>
            <h5>Step three <strong>(Important!)</strong></h5>
            <p>Once you've decided what you want to borrow, you need to use our kit <a href="{% url 'kit:kitLogout' %}">logout</a> system to mark what you want to borrow. This system has a number of advantages for you.</p>
            <ul>
              <li>You can view what's available to borrow. Only items highlighted in green are available, the rest are either too damaged to use or already in use.</li>
              <li>You can see information about all the equipment we have such as sizes, ability range, and more. This should make it easier to find what you want in the container.</li>
            </ul>
            <p>To borrow something, simply click the borrow button and thats it! Don't click items you don't want to borrow accidently or you could be marked as responsible for that item. To check whether something is marked as borrowed by you, items with a green "Return" button next to them are currently checked out by you.</p>
            <h5>Step four</h5>
            <p>Next message our kit sec, either by messaging the <a href="{{ facebook }}" target="_blank">Facebook Page</a>, emailing us at info@susurf.co.uk, or messaging the kit sec directly! They will then arrange a time for a committee member to go with you to collect the kit you need.</p>
            <h5>Step five</h5>
            <p>Go collect the kit you borrowed from the container! Our container is located in Wide Lane Sports Ground.</p>
            <div id="googleMap" style="width:100%;height:20em;"></div>
            <h5 style="padding-top:2em;">Step six</h5>
            <p>Once you've finished with the kit, message our kit sec again to arrange to return it. Please return kit as soon as possbile so other people can use it! So unless you're going surfing again in the next few days, please take it back!</p>
            <p>We may need to recall kit if we are running day / weeekend trips as these will always take priority! Otherwise you're welcome to borrow any kit as long as you follow this process.</p>
        </div>
    </div>
</div>

<script>
function myMap() {
var mapProp= {
  center:new google.maps.LatLng(50.950446, -1.365373),
  zoom:15,
};

var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);

var marker = new google.maps.Marker({position: mapProp.center});

marker.setMap(map);
}



</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBTX5h1RP_CzBFez0e1_yHXQ07Co1lQARk&callback=myMap"></script>
{% endblock %}

kit/templates/kit/kitCare.html
{% extends "base.html" %}

{% block main %}

<div class="container-fluid" style="padding-top: 3em; padding-bottom: 6em;">
    <div class="row content">
        <div class="container">
            <h2><strong>How to look after club kit?</strong></h2>
            <p>Please read this short guide on how to look after club kit. I'll highlight a few small things you can do to reduce how often we have to replace kit! (and to keep the kit you borrow in better condition!)</p>
            <h5 style="padding-top: 2em">Surfboards</h5>
            <p>In general surfboards are pretty delicate (especially hardboards) so treat them with lots of care!</p>
            <ul>
              <li>NEVER drag your board across the beach... or the carpark (I've seen it happen!)</li>
              <li>Don't drag your leash! Wrap it around your board when you aren't in the water (It also makes you look like a K00k)</li>
              <li>When strapping boards to rooves remove fins if it's a hardboard, and if it's a foamie make sure that fins aren't digging into another board. Stacking board from biggest to smallest can help you do this.</li>
              <li>Don't tighten strap tooo tight (They can dig into the rails of boards and damage them). Tighten them just enough to stop the boards moving around at all. (also remove leashes before putting boards on a roof)</li>
              <li>When putting your board down after a session do so gently and don't yeet it at the carpark. And try not to stack boards of top of each other if there's a hardboard involved.</li>
              <li>If you're taking a hardboard out make sure there are no holes in it! If there are and you take it in the water this can permenantly damage the board. Let a member of the committee know.</li>
              <li>If a board is marked as "Damaged" on the please don't borrow it (mainly for the reason above)</li>
            </ul>
            <h5>Wetsuits</h5>
            <p>Wetsuits need a bit of care to keep them stretchy and warm (and hole free) for a long time.</p>
            <ul>
              <li>After you're finished with your wetsuit, make sure to wash it! Salt isn't great for suits long term so give it a good rinse in a big bucket of cold water. At the container we have buckets for washing wetsuits, and theres a tap and hose round the back of the container building.</li>
              <li>When drying out (or generally hanging up) wetsuits don't hang them by the neck EVER! This will strech out the neck pretty quickly and then water will pour in when it's worn. Instead hang it by the waist through the hanger.</li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}

kit/templates/kit/kitHome.html
{% extends "base.html" %}

{% block main %}

<div class="container-fluid" style="padding-top: 3em; padding-bottom: 6em;">
    <div class="row content">
        <div class="container">
            <h2><strong>What kit do SuSurf Have?</strong></h2>
            <p>SuSurf has a large amount of kit that can be borrowed free of charge by its members! We have a large collection of boards, wetsuits, and other misc. gear for member use.</p>
            <ul>
                <li>Large Foamie Boards</li>
                <li>Hard Minimals (Bics)</li>
                <li>Foamie Shortboards</li>
                <li>Fibreglass Shortboards</li>
                <li>Mens and Womens Winter Wetsuits</li>
                <li>Leashes</li>
                <li>Soft Roof Racks</li>
            </ul>  
            <p>All kit is available to borrow to paid members, however if there is a club trip, this will take priority on kit required.</p>
        </div>
    </div>
    <div class="row content" style="padding-top: 3em; text-align: center;">
      <div class="card-deck mx-auto w-50">
          <div class="card text-white bg-dark">
            <div class="card-body">
                <h5 class="card-title">Borrowing</h5>
                <p class="card-text">How do I borrow club kit?</p>
                <a href="{% url 'kit:kitBorrowing' %}" class="btn btn-primary">Guide</a>
            </div>
          </div>
          <div class="card text-white bg-dark">
            <div class="card-body">
                <h5 class="card-title">Kit Care</h5>
                <p class="card-text">How do I look after club kit?</p>
                <a href="{% url 'kit:kitCare' %}" class="btn btn-primary">Guide</a>
            </div>
          </div>
        </div>
    </div>
    <div class="row" style="padding-top: 2em; text-align: center;">
      <div class="col-md">
        <div class="card w-50 mx-auto text-white" style="background-color: #3547E6;">
          <div class="card-body">
            <h5 class="card-title">Kit Borrowing System</h5>
            <a href="{% url 'kit:kitLogout' %}" class="btn btn-danger">View Kit</a>
          </div>
        </div>
      </div>
    </div>
</div>

{% endblock %}

kit/templates/kit/kitLogout.html
{% extends "base.html" %}

{% block style %}
tr.hide { display:none; }
{% endblock %}

{% block js %}
<script>
hideRows = function(dropdown, show, table, hideItems) {
    var drop = document.getElementById(dropdown);
    drop.innerText = show;
    var table = document.getElementById(table);
    for (var i = 0, row; row = table.rows[i]; i++) {
       row.classList.remove("hide");
       for (var j = 0, col; col = row.cells[j]; j++) {
          if (hideItems.includes(col.innerText)) {
            row.classList.add('hide');
            console.log("hidetrigged");
          }
       }  
}
    };
</script>
{% endblock %}

{% block main %}

<div class="container-fluid" style="padding-top: 3em; padding-bottom: 3em;">
  <div class="jumbotron jumbotron-fluid bg-dark text-white">
  <div class="row">
      <div class="col">
        <h1 class="display-5" style="text-align: center;">Surfboards</h1>
      </div>
      <div class="col">
        <div class="dropdown" style="text-align: center;">
          <button class="btn btn-secondary dropdown-toggle" style="width: 10em;" type="button" id="surfboardSort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sort Ability
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" onclick="hideRows('surfboardSort', 'Beginner', 'surfboardTable', ['Intermediate', 'Advanced']);">Beginner</a>
            <a class="dropdown-item" onclick="hideRows('surfboardSort', 'Intermediate', 'surfboardTable', ['Beginner', 'Advanced']);">Intermediate</a>
            <a class="dropdown-item" onclick="hideRows('surfboardSort', 'Advanced', 'surfboardTable', ['Beginner', 'Intermediate']);">Advanced</a>
            <a class="dropdown-item" onclick="hideRows('surfboardSort', 'All', 'surfboardTable', ['none']);">All</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table" id="surfboardTable" class="d-flex">
      <thead>
        <tr>
          <th scope="col" style="width:20%">ID Number</th>
          <th scope="col" style="width:15%">Brand</th>
          <th scope="col" style="width:15%">Model</th>
          <th scope="col" style="width:15%">Size</th>
          <th scope="col" style="width:15%">Ability</th>
          <th scope="col" style="width:20%"></th>
        </tr>
      </thead>
      <tbody>
        {% for board in surfboards %}
        {% if board.watertight == True %}
          {% if board.location == "Container" %}
          <tr class="table-success">
          {% else %}
          <tr class="table-danger">
          {% endif %}
        {% else %}
        <tr class="table-danger"> 
        {% endif %}
          <td>{{ board.IDnumber}}</td>
          <td>{{ board.brand }}</td>
          <td>{{ board.model }}</td>
          <td>{{ board.size }}</td>
          <td>{{ board.ability }}</td>
          {% if board.watertight == False %}
          <td>Damaged</td>
          {% elif board.location == "Container" %}
          <td><a role="button" href="{% url 'kit:takeBoard' ID=board.IDnumber %}" class="btn btn-danger">Borrow</button></td>
          {% elif board.location == user.email %}
          <td><a role="button" href="{% url 'kit:returnBoard' ID=board.IDnumber %}" class="btn btn-success">Return</button></td>
          {% else %}
            {% if user.is_staff == True %}
            <td>{{ board.location }}</td>
            {% else %}
            <td>In Use</td>
            {% endif %}
          {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="jumbotron jumbotron-fluid bg-dark text-white">
      <div class="row">
      <div class="col">
        <h1 class="display-5" style="text-align: center;">Wetsuits</h1>
      </div>
      <div class="col">
        <div class="dropdown" style="text-align: center;">
          <button class="btn btn-secondary dropdown-toggle" style="width: 10em;" type="button" id="wetsuitSort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sort Gender
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" onclick="hideRows('wetsuitSort', 'Womens', 'wetsuitTable', ['Mens Small', 'Mens Medium', 'Mens Large', 'Mens Extra Large']);">Womens</a>
            <a class="dropdown-item" onclick="hideRows('wetsuitSort', 'Mens', 'wetsuitTable', ['Womens 6', 'Womens 8', 'Womens 10', 'Womens 12', 'Womens 14', 'Womens 16']);">Mens</a>
            <a class="dropdown-item" onclick="hideRows('wetsuitSort', 'All', 'wetsuitTable', ['none']);">All</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table" id="wetsuitTable" class="d-flex">
      <thead>
        <tr>
          <th scope="col" style="width:20%">ID Number</th>
          <th scope="col" style="width:15%">Brand</th>
          <th scope="col" style="width:15%">Model</th>
          <th scope="col" style="width:15%">Size</th>
          <th scope="col" style="width:15%">Thickness</th>
          <th scope="col" style="width:20%"></th>
        </tr>
      </thead>
      <tbody>
        {% for suit in wetsuits %}
        {% if suit.usable == True %}
          {% if suit.location == "Container" %}
          <tr class="table-success">
          {% else %}
          <tr class="table-danger">
          {% endif %}
        {% else %}
        <tr class="table-danger"> 
        {% endif %}
          <td>{{ suit.IDnumber}}</td>
          <td>{{ suit.brand }}</td>
          <td>{{ suit.model }}</td>
          <td>{{ suit.size }}</td>
          <td>{{ suit.thickness }}</td>
          {% if suit.usable == False %}
          <td>Damaged</td>
          {% elif suit.location == "Container" %}
          <td><a role="button" href="{% url 'kit:takeSuit' ID=suit.IDnumber %}" class="btn btn-danger">Borrow</button></td>
          {% elif suit.location == user.email %}
          <td><a role="button" href="{% url 'kit:returnSuit' ID=suit.IDnumber %}" class="btn btn-success">Return</button></td>
          {% else %}
            {% if user.is_staff == True %}
            <td>{{ suit.location }}</td>
            {% else %}
            <td>In Use</td>
            {% endif %}
          {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="jumbotron jumbotron-fluid bg-dark text-white">
    <div class="container">
      <h1 class="display-5">Leashes</h1>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table" id="adminTable">
      <thead>
        <tr>
          <th scope="col" style="width:80%">ID Number</th>
          <th scope="col" style="width:20%"></th>
        </tr>
      </thead>
      <tbody>
        {% for miscItem in misc %}
          {% if miscItem.item_type == "Leash" %}
          {% if miscItem.location == "Container" %}
          <tr class="table-success">
          {% else %}
          <tr class="table-danger">
          {% endif %}
          <td>{{ miscItem.IDnumber}}</td>
          {% if miscItem.location == "Container" %}
          <td><a role="button" href="{% url 'kit:takeMisc' ID=miscItem.IDnumber %}" class="btn btn-danger">Borrow</button></td>
          {% elif miscItem.location == user.email %}
          <td><a role="button" href="{% url 'kit:returnMisc' ID=miscItem.IDnumber %}" class="btn btn-success">Return</button></td>
          {% else %}
            {% if user.is_staff == True %}
            <td>{{ miscItem.location }}</td>
            {% else %}
            <td>In Use</td>
            {% endif %}
          {% endif %}
          </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="jumbotron jumbotron-fluid bg-dark text-white">
    <div class="container">
      <h1 class="display-5">Other</h1>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table" id="adminTable">
      <thead>
        <tr>
          <th scope="col" style="width:20%">ID Number</th>
          <th scope="col" style="width:60%">Item</th>
          <th scope="col" style="width:20%"></th>
        </tr>
      </thead>
      <tbody>
        {% for miscItem in misc %}
          {% if miscItem.item_type != "Leash" %}
          {% if miscItem.location == "Container" %}
          <tr class="table-success">
          {% else %}
          <tr class="table-danger">
          {% endif %}
          <td>{{ miscItem.IDnumber}}</td>
          <td>{{ miscItem.item_type}}</td>
          {% if miscItem.location == "Container" %}
          <td><a role="button" href="{% url 'kit:takeMisc' ID=miscItem.IDnumber %}" class="btn btn-danger">Borrow</button></td>
          {% elif miscItem.location == user.email %}
          <td><a role="button" href="{% url 'kit:returnMisc' ID=miscItem.IDnumber %}" class="btn btn-success">Return</button></td>
          {% else %}
            {% if user.is_staff == True %}
            <td>{{ miscItem.location }}</td>
            {% else %}
            <td>In Use</td>
            {% endif %}
          {% endif %}
          </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}