blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = 'blog'
urlpatterns = [
    path('blog/', views.blogList, name='blogList'),  
    path('blog/<int:blogID>/', views.blogDetail, name='blogDetail'),  
]

events/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'events'
urlpatterns = [
    path('events/', views.eventsPage, name='events'),
    path('events/<int:eventID>/', views.eventDetail, name='eventDetail'),
    path('events/<int:eventID>/signup', views.signup, name='signup'),
    path('events/signupConfirm', views.signupConfirmation, name='confirmation'),
    path('events/<int:eventID>/admin', views.eventAdmin, name='eventAdmin'),
]

kit/urls.py
from django.urls import path

from . import views

app_name = 'kit'
urlpatterns = [
    path('kit', views.kitHome, name='kitHome'),
    path('kit/logout', views.kitLogout, name='kitLogout'),
    path('kit/borrowing', views.kitBorrowing, name='kitBorrowing'),
    path('kit/care', views.kitCare, name='kitCare'),
    path('kit/logout/takeBoard/<int:ID>', views.takeBoard, name='takeBoard'),
    path('kit/logout/returnBoard/<int:ID>', views.returnBoard, name='returnBoard'),
    path('kit/logout/takeSuit/<int:ID>', views.takeSuit, name='takeSuit'),
    path('kit/logout/returnSuit/<int:ID>', views.returnSuit, name='returnSuit'),
    path('kit/logout/takeMisc/<int:ID>', views.takeMisc, name='takeMisc'),
    path('kit/logout/returnMisc/<int:ID>', views.returnMisc, name='returnMisc'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import password_reset_request

urlpatterns = [
	path('', include('pages.urls')),
    path('', include('users.urls')),
    path('', include('events.urls')),
    path('', include('kit.urls')),
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),

    #Password Reset URLS
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset", password_reset_request, name="password_reset"),
]

admin.site.site_header = 'SuSurf Site Admin'
admin.site.site_title = 'SUSURF'

pages/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = 'pages'
urlpatterns = [
    path('', views.homePage, name='home'),
    path('about/', views.aboutPage, name='about'),
    path('committee/', views.committeePage, name='committee'),
    path('join/', views.joinPage, name='join'),
    #Resources
    path('spots/', views.spotsPage, name='spots'),
    path('spots/<str:spot>/', views.spot_detail, name='spots_detail'),
    
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup/confirmed', views.signupConfirmation, name='signupConfirmation'),

    path('login/', views.login_req, name='login_req'),
    path('logout/', views.logout_req, name='logout_req'),

    path('password_change/', views.password_change, name='password_change'),
    path('password_change/confirm', views.passwordChangeConfirmed, name='passwordChangeConfirmed'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <!-- Favicon -->
  <link rel="icon" href="/static/logo.png">
  <!-- Required meta tags (BS) -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  {% block js %}
  {% endblock %}
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <!-- Social Buttons CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
  {% block style %}
  {% endblock %}
  </style>

  <title>{{ title|default:"SUSURF" }}</title>

</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'pages:home' %}">
        <img src="/static/logo.png" class="brand" alt="SUSURF" style="width: 3em;">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav">

          {% if currentPage == "Home" %}
          <li class="nav-item active">
          {% else %}
          <li class="nav-item">
          {% endif %}
            <a class="nav-link" href="{% url 'pages:home' %}">Home
              <span class="sr-only">(current)</span>           
            </a>
          </li>

          {% if currentPage == "Events" %}
          <li class="nav-item active">
          {% else %}
          <li class="nav-item">
          {% endif %}
            <a class="nav-link" href="{% url 'events:events' %}">Events</a>
          </li>

          {% if currentPage == "About" %}
          <li class="nav-item active">
          {% else %}
          <li class="nav-item">
          {% endif %}
            <a class="nav-link" href="{% url 'pages:about' %}">About</a>
          </li>

          {% if currentPage == "Committee" %}
          <li class="nav-item active">
          {% else %}
          <li class="nav-item">
          {% endif %}
            <a class="nav-link" href="{% url 'pages:committee' %}">Committee</a>
          </li>

          {% if currentPage == "Blog" %}
          <li class="nav-item active">
          {% else %}
          <li class="nav-item">
          {% endif %}
            <a class="nav-link" href="{% url 'blog:blogList' %}">Blog</a>
          </li>

          {% if currentPage == "Kit" %}
          <li class="nav-item active">
          {% else %}
          <li class="nav-item">
          {% endif %}
            <a class="nav-link" href="{% url 'kit:kitHome' %}">Kit</a>
          </li>
          
          {% if currentPage == "Resources" %}
          <li class="nav-item dropdown active">
          {% else %}
          <li class="nav-item dropdown">
          {% endif %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Resources
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
<!--          <a class="dropdown-item" href="#">Edits</a> -->
              <a class="dropdown-item" href="{% url 'pages:spots' %}">Spots</a>
<!--          <a class="dropdown-item" href="#">Trip Guide</a> -->
            </div>
          </li>
        </ul>
        {% if request.user.is_staff %}
          <a href="{% url 'admin:index' %}" class="btn btn-danger btn-signup" role="button">Admin</a>
        {% endif %}
        <form class="form-inline ml-auto">
          {% if request.user.is_authenticated %}
          <a style="color: white; padding-right: 10px;">
            {{ request.user.first_name }} {{ request.user.last_name }}
          </a>

          <div class="btn-group">
            <a href="{% url 'users:logout_req' %}" class="btn btn-primary btn-signup" role="button">Logout</a>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="{% url 'users:password_change' %}">Change Password</a>
            </div>
          </div>
          {% else %}
          <a href="{% url 'users:login_req' %}" class="btn btn-light btn-signup" role="button">Login</a>
          <a href="{% url 'users:signup' %}" class="btn btn-secondary btn-signup" role="button">Sign Up</a>
          {% endif %}
       </form>
      </div>
  </nav>

  {% block main %}
  {% endblock %}

  <!-- Footer -->
  <footer class="footer py-4 bg-dark">
    <div class="container">
      <div class="row">
        <div class="col">
          <a href="{{ susu }}" target="_blank">
            <img src="/static/susu.png" style="width: 5em;">
          </a>
        </div>
        <div class="col; text-muted" style="text-align: center;">
          {{ footer|default:"nothing" }}
        </div>
        <div class="col" style="text-align:right">
          <a href="{{ facebook }}" target="_blank">
            <img src="/static/facebook.png" class="brand" alt="Facebook" style="width: 2.5em;">
          </a>
          <a href="{{ instagram }}" target="_blank">
            <img src="/static/instagram.png" class="brand" alt="Instragram" style="width: 2.5em;">
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col">
        </div>
        <div class="col; text-link" style="text-align: center;">
          <a href = "mailto: enquiries.susurf@gmail.com">{{ email|default:"x@x" }}</a>
        </div>
        <div class="col">
        </div>
      </div>
    </div>
  </footer>

</body>

</html>